name: Inception

services:
  nginx:
    image: nginx
    build:
      dockerfile: requirements/nginx/Dockerfile
    # volumes:
    #   - /home/mbirou/data/html:/var/www/html
    volumes_from:
      - wordpress
    ports:
      - 443:443
    depends_on:
      - wordpress
    env_file: ".env"
    restart: unless-stopped
    networks:
      inception:

  wordpress:
    image: wordpress
    build:
      dockerfile: requirements/wordpress/Dockerfile
    depends_on:
      - mariadb
    env_file: ".env"
    restart: unless-stopped
    volumes: 
      - /home/mbirou/data/html:/var/www/html
    networks:
      inception:

  mariadb:
    image: mariadb
    build:
      dockerfile: requirements/mariadb/Dockerfile
    env_file: ".env"
    restart: unless-stopped
    volumes:
      - /home/mbirou/data/DB:/var/lib/mariadb
    networks:
      inception:

networks:
  inception:
    driver: bridge
