/* function.c generated by valac 0.57.0.224-bccf, the Vala compiler
 * generated from function.vala, do not modify */

#include <glib.h>

#if !defined(VALA_EXTERN)
#if defined(_WIN32) || defined(__CYGWIN__)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

VALA_EXTERN void ra (GQueue* s_a);
VALA_EXTERN void rra (GQueue* s_a);
VALA_EXTERN void pb (GQueue* s_a,
         GQueue* s_b);
VALA_EXTERN void pa (GQueue* s_a,
         GQueue* s_b);
VALA_EXTERN void rb (GQueue* s_b);
VALA_EXTERN void rrb (GQueue* s_b);
VALA_EXTERN void rr (GQueue* s_a,
         GQueue* s_b);
VALA_EXTERN void rrr (GQueue* s_a,
          GQueue* s_b);
VALA_EXTERN void sa (GQueue* s_a);
VALA_EXTERN void sb (GQueue* s_b);
VALA_EXTERN void ss (GQueue* s_a,
         GQueue* s_b);

void
ra (GQueue* s_a)
{
	gint tmp = 0;
	gpointer _tmp0_;
	g_return_if_fail (s_a != NULL);
	_tmp0_ = g_queue_pop_head (s_a);
	tmp = (gint) ((gintptr) _tmp0_);
	g_queue_push_tail (s_a, (gpointer) ((gintptr) tmp));
}

void
rra (GQueue* s_a)
{
	gint tmp = 0;
	gpointer _tmp0_;
	g_return_if_fail (s_a != NULL);
	_tmp0_ = g_queue_pop_tail (s_a);
	tmp = (gint) ((gintptr) _tmp0_);
	g_queue_push_head (s_a, (gpointer) ((gintptr) tmp));
}

void
pb (GQueue* s_a,
    GQueue* s_b)
{
	gint tmp = 0;
	gpointer _tmp0_;
	g_return_if_fail (s_a != NULL);
	g_return_if_fail (s_b != NULL);
	_tmp0_ = g_queue_pop_head (s_a);
	tmp = (gint) ((gintptr) _tmp0_);
	g_queue_push_head (s_b, (gpointer) ((gintptr) tmp));
}

void
pa (GQueue* s_a,
    GQueue* s_b)
{
	gint tmp = 0;
	gpointer _tmp0_;
	g_return_if_fail (s_a != NULL);
	g_return_if_fail (s_b != NULL);
	_tmp0_ = g_queue_pop_head (s_b);
	tmp = (gint) ((gintptr) _tmp0_);
	g_queue_push_head (s_a, (gpointer) ((gintptr) tmp));
}

void
rb (GQueue* s_b)
{
	gint tmp = 0;
	gpointer _tmp0_;
	g_return_if_fail (s_b != NULL);
	_tmp0_ = g_queue_pop_head (s_b);
	tmp = (gint) ((gintptr) _tmp0_);
	g_queue_push_tail (s_b, (gpointer) ((gintptr) tmp));
}

void
rrb (GQueue* s_b)
{
	gint tmp = 0;
	gpointer _tmp0_;
	g_return_if_fail (s_b != NULL);
	_tmp0_ = g_queue_pop_tail (s_b);
	tmp = (gint) ((gintptr) _tmp0_);
	g_queue_push_head (s_b, (gpointer) ((gintptr) tmp));
}

void
rr (GQueue* s_a,
    GQueue* s_b)
{
	g_return_if_fail (s_a != NULL);
	g_return_if_fail (s_b != NULL);
	ra (s_a);
	rb (s_b);
}

void
rrr (GQueue* s_a,
     GQueue* s_b)
{
	g_return_if_fail (s_a != NULL);
	g_return_if_fail (s_b != NULL);
	rra (s_a);
	rrb (s_b);
}

void
sa (GQueue* s_a)
{
	gint tmp1 = 0;
	gpointer _tmp0_;
	gint tmp2 = 0;
	gpointer _tmp1_;
	g_return_if_fail (s_a != NULL);
	_tmp0_ = g_queue_pop_head (s_a);
	tmp1 = (gint) ((gintptr) _tmp0_);
	_tmp1_ = g_queue_pop_head (s_a);
	tmp2 = (gint) ((gintptr) _tmp1_);
	g_queue_push_head (s_a, (gpointer) ((gintptr) tmp1));
	g_queue_push_head (s_a, (gpointer) ((gintptr) tmp2));
}

void
sb (GQueue* s_b)
{
	gint tmp1 = 0;
	gpointer _tmp0_;
	gint tmp2 = 0;
	gpointer _tmp1_;
	g_return_if_fail (s_b != NULL);
	_tmp0_ = g_queue_pop_head (s_b);
	tmp1 = (gint) ((gintptr) _tmp0_);
	_tmp1_ = g_queue_pop_head (s_b);
	tmp2 = (gint) ((gintptr) _tmp1_);
	g_queue_push_head (s_b, (gpointer) ((gintptr) tmp1));
	g_queue_push_head (s_b, (gpointer) ((gintptr) tmp2));
}

void
ss (GQueue* s_a,
    GQueue* s_b)
{
	g_return_if_fail (s_a != NULL);
	g_return_if_fail (s_b != NULL);
	sa (s_a);
	sb (s_b);
}

